[versions]
agp = "8.8.0-alpha05"
kotlin = "2.0.0"
appcompat = "1.7.0"
material = "1.12.0"
appcompatV7 = "28.0.0"
activity = "1.10.0"
constraintlayout = "2.2.0"
kotlin_parcelize = "2.1.20-Beta1"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
appcompat-v7 = { group = "com.android.support", name = "appcompat-v7", version.ref = "appcompatV7" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "kotlin-parcelize" }
android-library = { id = "com.android.library", version.ref = "agp" }

